### ISSUE TITLE
move latest source from qps-pipeline repo using develop branch

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#1]
We agreed to start from scratch using clean and new pipeline-ce repo inside zebrunner org for jenkins pipeline/jobdsl scripting.

**Comment by vdelendik** [comment]
done.
to test please update in jenkins manually in global vars:
variant #1:
QPS_PIPELINE_BRANCH=master
QPS_PIPELINE_GIT_URL=https://github.com/zebrunner/pipeline-ce
-> sanity check with repository scanner and api jobs run should be good.

variant #2:
QPS_PIPELINE_BRANCH=1.0
QPS_PIPELINE_GIT_URL=https://github.com/zebrunner/pipeline-ce
-> sanity check with repository scanner and api jobs run should be good.

**Comment by dhreben** [comment]
Test scenario:

Variant 1:

1.Open Jenkins
2.Tap Manage Jenkins
3.Tap Configure system
4.Set QPS_PIPELINE_BRANCH=master and QPS_PIPELINE_GIT_URL=https://github.com/zebrunner/pipeline-ce
5.Open reporting and run scanner
6.Check that scanner work correctly
7.Run API-Demo-Test and check that the build succeeded.

Variant 2:

1.Open Jenkins
2.Tap Manage Jenkins
3.Tap Configure system
4.Set QPS_PIPELINE_BRANCH=1.0 and QPS_PIPELINE_GIT_URL=https://github.com/zebrunner/pipeline-ce
5.Open reporting and run scanner
6.Check that scanner work correctly
7.Run API-Demo-Test and check that the build succeeded.

Variant 3:

1.Open Jenkins
2.Tap Manage Jenkins
3.Tap Configure system
4.Remove/declare invalid value for QPS_PIPELINE_BRANCH
5.Set QPS_PIPELINE_GIT_URL=https://github.com/zebrunner/pipeline-ce
6.In Retrieval method tick Modern SCM
7.In Source Code Management  -> Project Repository add https://github.com/zebrunner/pipeline-ce.git 
8.Open API-Demo-Test
9.Tap configure
10.Scroll down the page and add to the pipeline script version branch 1.0 
   - @Library('QPS-Pipeline') -> @Library('QPS-Pipeline@1.0') then apply and save.

11.Run API-Demo-Test and check that the build succeeded.

It is important to add curl **https://github.com/zebrunner/pipeline-ce.git**  for correct work  "Modern SCM" in Source Code Management -> Project Repository
