### ISSUE TITLE
improve sonar analysis adding provider (github or gitlab)

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#11]
sonar onPR or onPush evens analysis should specify explicitly 
sonar.pullrequest.provider=...
default value in groovy pipeline code: Github

But if current job has GITHUB_HOST=gitlab.com we have to specify 
sonar.pullrequest.provider=GitlabServer

for bitbucket
sonar.pullrequest.provider=BitbucketServer

**Comment by sandinosanchez** [comment]
This ticket is verified against #5 test steps.
