### ISSUE TITLE
disable queue registration

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#111]
After set of discussions this feature is marked for removal as it blocks new functionality with projects.
Let's disable this call in 1.4 and remove completely in 1.5 release.

Also we have to remove jenkinsQueueRegistration from jobDSL suppotr and documentation: https://zebrunner.github.io/zebrunner/user-guide/#special-annotations

**Comment by vdelendik** [comment]
commented in 1.4: https://github.com/zebrunner/pipeline-ce/pull/113/files

**Comment by vdelendik** [comment]
done, all queue registration logic removed:
- jobdsl argument
- hidden test job field
- methods in zafira client and updater

Also documentation for zebrunner/zebrunner repo adjusted: https://github.com/zebrunner/zebrunner/commit/8f9f2b7ed331493018c14c30b203216032e8145e

During the testing make sure we can do a sanity check with registration of api/web tests

**Comment by okamara** [comment]
Verified on dev. Fixed.
