### ISSUE TITLE
'Null' artifact is added to all test runs on test run grid

### ISSUE THREAD

**Issue by Anna-Kopachova** [zebrunner/pipeline-ce#118]
**Steps to reproduce:**
1. Login to Zebrunner staging
2. Open test run grid and run any test job from Launcher
3. Check test run artifacts before/after the job is finished

**Expected result:** Test runs shouldn't have 'Null' artifact attached. 
**Actual result:** All finished test runs have 'Null' artifact attached.
**Repro rate: 7/7**

**Environment:** 
ui: 1.19.0.RC6 
server: 1.19.0.RC5

![image](https://user-images.githubusercontent.com/74259363/105689446-d6536280-5f0b-11eb-8937-ca808b27de10.png)

**Comment by vdelendik** [comment]
fixed. 
@Anna-Kopachova, changes might be tested using develop branch (stag is ok)

**Comment by okamara** [comment]
Verified on master. Fixed.
