### ISSUE TITLE
adjust cucumber reports publishing after changes in carina

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#12]
We have to apply new logic and remove existing workaround after fixing on core level:
https://github.com/qaprosoft/carina/issues/816

**Comment by vdelendik** [comment]
among changes:
1. don't publish CarinaReport anymore as it has too many small files and occupy HDD a lot
2. CucumberReport published using updated location for 7.0.0-SNAPSHOT carina
3. don't publish `Full TestNG HTML Report` and `TestNG Summary HTML Report` reports anymore as well

**Comment by dhreben** [comment]
Verified.

**Comment by vdelendik** [comment]
verified as well:
![image](https://user-images.githubusercontent.com/4551455/104742809-f6d92b00-575b-11eb-86be-fd97534d4db9.png)
