### ISSUE TITLE
onPush job is not triggered for Bitbucket pull request

### ISSUE THREAD

**Issue by ghost** [zebrunner/pipeline-ce#121]
Steps:
1. Set up Webhook for bitbucket via instruction https://zebrunner.github.io/zebrunner/config-guide/#pull-request-decoration-example
2. Change Read.me file and sent pull request from test job to master
3. Verify in jenkins that onPush job is started
Actual result: onPush job is started in jenkins

**Comment by vdelendik** [comment]
@okamara, @dhreben - let's retest again using the same steps: https://zebrunner.github.io/community-edition/integration/scm/
I hope new plugin in jenkins could handle this use-case as well. if not - reopen again.

**Comment by dhreben** [comment]
Still repro

**Comment by azarouski** [comment]
PR - https://github.com/zebrunner/pipeline-ce/pull/310

**Comment by azarouski** [comment]
Need to test again

**Comment by dhreben** [comment]
` java.util.MissingFormatArgumentException: Format specifier '%s'` after create RegisterRepository

**Comment by vdelendik** [comment]
@dhreben - make sure RegisterRepository has latest `develop` pipeline branch for Zebrunner-CE.
Based on the error it uses master or main...

**Comment by azarouski** [comment]
wontfix, onPush job should not be triggered with onPullRequest action
