### ISSUE TITLE
review if createJobs is used and remove if not

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#122]
https://github.com/zebrunner/pipeline-ce/blob/42a0230c5f9cf57d1d437f6241f195af03abcbd4/src/com/zebrunner/jenkins/pipeline/integration/zafira/ZafiraClient.groovy#L211

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/pipeline-ce/commit/d63a6b33d25b4f79e32490f25bd7d8295829c350
as a test just run api and web and make sure everything registered correctly in reporting

**Comment by okamara** [comment]
Verified on dev. branch. Fixed.

**Comment by okamara** [comment]
Separate issue was created https://github.com/zebrunner/zebrunner/issues/423
