### ISSUE TITLE
aborted run by timeout don't execute abort call for reporting

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#127]
We moved abort testrun code from finally to catch block but maven don't think it is a failure and finish with valid exit code.
So it should be moved back to finally and appropriate comment placed to describe this concrete use-case

**Comment by vdelendik** [comment]
fixed. all notifications moved onto the finally block with extra testRun.status verification.
is status equals IN_PROGRESS or QUEUED we explicitly execute abort call.

Test scenario:
1. setup zebrunner from develop branch and start services
2. update ZEBRUNNER_VERSION among global variables to `develop`
3. register org and carina-demo as repository
4. launch Web-Demo-Test job
5. while job in progress abort job in jenkins
-> in reporting run should be aborted, run comment should have something like `Aborted by admin`
-> Published ZafiraReport should have ABORTED staus as well

**Comment by dhreben** [comment]
Fixed

<img width="420" alt="Screenshot 2021-04-01 at 19 59 59" src="https://user-images.githubusercontent.com/50950954/113328375-e2e9a200-9324-11eb-8878-2692baf33d5f.png">


<img width="1313" alt="Screenshot 2021-04-01 at 19 58 17" src="https://user-images.githubusercontent.com/50950954/113328309-cc434b00-9324-11eb-9886-f48a7f25f30e.png">
