### ISSUE TITLE
delete organization job should remove custom project based security

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#13]
DeletOrganization pipeline should delete custom "Project-based Matrix Authorization Strategy" authorization if any.
@ilya-varchenya - ask @tsvrko about details

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/pipeline-ce/commit/e2b58df33d36627c9092e79b1e1bea0563335d56

as a test scenario:
1. register custom org on stage zebrunner cloud
2. scan any folder and run 1-2 jobs
3. to make a process more complex visit jenkins_urls/configureSecurity/ and assign more permissions in additions to read for your user
4. run tenant removal process
-> default "read" and all customized permissions for your user should be removed completely from jenkins_urls/configureSecurity/

**Comment by okamara** [comment]
Verified. Fixed.
