### ISSUE TITLE
update onPush and onPullRequest job descriptions

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#130]
1. remove out-of-dated info about github webhook usage
2. provide links to the documentation where we have up-to-date information

**Comment by vdelendik** [comment]
fixed.
after registering the repo using develop zebrunner pipeline branch we should have new job descriptions for onPush and onPullRequest system jobs
1. setup from develop
2. update ZEBRUNNER_VERSION to develop in global jenkins variables
3. register new oranization
4. register new repo (carina-demo)
-> inspect onPR and onPush system jobs description
![image](https://user-images.githubusercontent.com/4551455/109710503-cab02700-7bae-11eb-86f4-66b80ce714c2.png)

**Comment by okamara** [comment]
Verified on dev.
