### ISSUE TITLE
Build job should run without git token (for open source)

### ISSUE THREAD

**Issue by okamara** [zebrunner/pipeline-ce#133]
Tested on develop brach

Steps:
1. Start Jenkins
2. Register Organization
3. Register repository scm user and token are empty
4. Run build job
Actual result: build job is faild
Expected result: Build job should run without git token (for open source)

**Comment by vdelendik** [comment]
fixed. @okamara next time please don't forget to attach logs or piece of logs with actual error message.
test scenario:
1. setup and register caarina-demo
2. run build job with "clean compile test" goals
-> job should fail with
```
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException
```
3. Edit build job updating library pipeline to `@Library('Zebrunner-CE@develop')`
4. run again using `clean compile test` goals
-> job should compile project successfully and execute default api test (nothing is registered to reporting  as expected!)

**Comment by okamara** [comment]
Verified. Fixed.
