### ISSUE TITLE
made enableVideo capabilitites true by default

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#134]
All our services configured by default with valid video recording options.
So we should be in a good shape to enable it by default.

**Comment by vdelendik** [comment]
done. enableVideo checkbox removed completely for all web/mobile jobs i.e. -1 field per job:)
to test make sure to 
1. update ZEBRUNNER_VERSION to develop
2. register one more time carina-demo repo
-> verify that there is no anymore enableVideo checkbox for web/mobile jobs
3. execute Web-Demo-Test
-> After finishing you should see video recording as this capability is enabled by default for selenium, zebrunner and mcloud providers

**Comment by dhreben** [comment]
Verified.
