### ISSUE TITLE
repo-github-webhook seems is updated everytime we re-register repo

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#138]
The process to setup github/gitlab etc integration include custom secure token usage which should be applied after registering the repo...
It seems like this token is resetted everytime we registerRepository which is not correct as manually adjusted value by administrator should persist.

Steps:
1. Setup pull request and push integration with github
-> for PR appropriate checker is initialized, for push to default branch onPush executed
2. run RegisterRepository again using the same data as before
3. Open github webhook url with token
`http://hostname/jenkins/generic-webhook-trigger/invoke?token=....`
-> no configured jobs are displayed and such message exists:
`{"jobs":null,"message":"Did not find any jobs with GenericTrigger configured! If you are using a token, you need to pass it like ...trigger/invoke?token=TOKENHERE. If you are not using a token, you need to authenticate like http://user:passsword@jenkins/generic-webhook... "}`

**Comment by vdelendik** [comment]
done.
To test use 1.4.4 or develop as ZEBRUNNER_PIPELINE.
1. Verify that after registering the jobs you have to check that below setting is applicable only for test and cron jobs:
![image](https://user-images.githubusercontent.com/4551455/109275954-7c093280-7826-11eb-9083-224dbeb5fb45.png)
2. Verify that onPullRequest and onPush system jobs don't have such fetaure enabled (it conflicts with generic web hook plugin)

**Comment by okamara** [comment]
Verified on develop branch.
ciStart is present in each job in "Management Jobs" + /jenkins/job/launcher.
onPullRequest and onPush system jobs doesn't have such feature enabled.

**Comment by vdelendik** [comment]
@okamara, you have to test all api/web jobs after registering repo. ciStart should present in each test job!

**Comment by okamara** [comment]
ciStart is not present in build, onPullRequest and onPush system jobs jobs
