### ISSUE TITLE
unit testing results for maven not available in sonarqube

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#142]
0% coverage report is displayed for any java maven repo: https://ci.zebrunner.com/sonarqube/component_measures?id=com.qaprosoft%3Acarina&metric=new_coverage&view=list

we have to investigate what can be done without restoring jacoco plugin or adding it only for test scope

**Comment by vdelendik** [comment]
fixed.
during the feature testing we have to setup with sonarqube and register 2 repos:
https://github.com/qaprosoft/carina.git
https://github.com/qaprosoft/carina-demo.git

after successful registration we should see in sonar for carina-demo 1 unit test
![image](https://user-images.githubusercontent.com/4551455/113355203-13dbce00-9349-11eb-8497-046a58c51f6a.png)

for carina - 334 unit tests (100% pass rate)
![image](https://user-images.githubusercontent.com/4551455/113355347-51d8f200-9349-11eb-91e4-95d719e29646.png)


Also put into the notes that PR checkers and onPush events should be tested in scope of final regression obligatory

**Comment by okamara** [comment]
Verified on develop brach. Unit tests are present
<img width="937" alt="Снимок экрана 2021-04-08 в 14 06 57" src="https://user-images.githubusercontent.com/32964663/114016654-bdecb600-9873-11eb-831c-f5811833030d.png">
<img width="953" alt="Снимок экрана 2021-04-08 в 14 06 37" src="https://user-images.githubusercontent.com/32964663/114016668-bfb67980-9873-11eb-9f2a-771f6a69b010.png">

**Comment by okamara** [comment]
PR checkers verified, works
