### ISSUE TITLE
Git tag checkout

### ISSUE THREAD

**Issue by mohamadli** [zebrunner/pipeline-ce#146]
I'd like to be able to checked out Git tag (like I can other Git objects: branch or commit)

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/pipeline-ce/pull/302

to test we have to register repository and execute any job using 3 approaches:
1. as regular using only branch name, for example `main`
2. refer to any specific tag, for example in carina-demo we have `refs/tags/1.0`
3. refer to any specific branch using full specs: `refs/heads/7.3.21.1699`

as result repository should be registered using above branches, jobs might be executed successfully. also review sha1 for the cloning operation. it should be the same as for branch and head in github.

**Comment by okamara** [comment]
Verified, fixed
