### ISSUE TITLE
find a way to provide valid project key via pipeline or directly from TestNG suite

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#147]
"zafira_project" TestNG parameter was deprecated in jan, 2021.
`reporting.project-key` is new key which can work with a key (not name!).

Migration path to reporting 1.23+ includes project name cut to key (6 first symbols).
So we have to decide what to do:
1. force users to update their testNG repositories accordingly
2. provide some pipeline logic and intermediate period when we continue to read zafira_project, cut it to 6 symbols and provide as `reporting.project-key` arg
3. force zebrunner agent to read this data on it's own during test startup

**Comment by vdelendik** [comment]
zafira_project removed completely including hidden field for the jobs.
Changes are available in pipeline_version: develop.

Tests can be executed only on stage cloud version so far where new project-service is deployed.
Also make sure to scan carina-demo repo from qaprosoft org and **branch: develop**
Inside this branch zafira_project TestNG suite file parameters were removed as well. After scanning make sure there is no hidden field for jobs as well and tests and can be executed and registered correctly

**Comment by okamara** [comment]
Verified on stage cloud version. Fized.
