### ISSUE TITLE
investigate possibility to support TestNG suite xml files from any location

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#148]
for now there is a limitation to place suite xml files into `src/test/resources` or `src/test/resources/testng_suites` for carina framework.
As result we can't scan and reuse repositories where xml suite files are located in other places, f.e. root folder.
Examine pipeline scanner code to avoid this limitation

**Comment by vdelendik** [comment]
fixed. moreover for non carina frameworks `suite` argument is optional now.

**Comment by okamara** [comment]
need more details for verification.

**Comment by okamara** [comment]
verified on develop branch, fixed.
