### ISSUE TITLE
do not provide any data for capabilities launcher to reporting

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#153]
subj

**Comment by vdelendik** [comment]
it should remove any customization of capabilities in reporting launcher.

**Comment by okamara** [comment]
launcher is not supported any more in Zebrunner ce.

**Comment by okamara** [comment]
Run:
docker exec -ti postgres bash
set schema 'zafira';
select * from launchers;
Expected: 0 notes
Actual result: there are 3 notes in the table
postgres=# select * from launchers;
 id |              name              |                                            model                                             | scm_id | job_i
d |  type   | auto_scan |        modified_at         |         created_at         
----+--------------------------------+----------------------------------------------------------------------------------------------+--------+------
--+---------+-----------+----------------------------+----------------------------
  1 | Carina WEB                     | {                                                                                           +|      1 |      
1 | web     | f         | 2021-06-15 10:26:20.023795 | 2021-06-15 10:26:20.023795
    |                                |                    "branch":"master",                                                       +|        |      
  |         |           |                            | 
    |                                |                    "capabilities.browserName":"chrome",                                     +|        |      
  |         |           |                            | 
    |                                |                    "suite":"web"                                                            +|        |      
  |         |           |                            | 
    |                                |                 }                                                                            |        |      
  |         |           |                            | 
  2 | Carina API                     | {                                                                                           +|      1 |      
1 | api     | f         | 2021-06-15 10:26:20.023795 | 2021-06-15 10:26:20.023795
    |                                |                    "capabilities.platformName":"API",                                       +|        |      
  |         |           |                            | 
    |                                |                    "branch":"master",                                                       +|        |      
  |         |           |                            | 
    |                                |                    "suite":"api"                                                            +|        |      
  |         |           |                            | 
    |                                |                 }                                                                            |        |      
  |         |           |                            | 
  3 | API-CustomParams-Demo          | {                                                                                           +|      1 |      
2 | api     | t         | 2021-06-15 12:18:10.115622 | 2021-06-15 11:05:59.795571
    |                                |     "env": [                                                                                +|        |      
  |         |           |                            | 
    |                                |         "DEMO"                                                                              +|        |      
  |         |           |                            | 
    |                                |     ],                                                                                      +|        |      
  |         |           |                            |

**Comment by vdelendik** [comment]
moved onto the 1.6 pipeline release. that's too risky to do a change in this period

**Comment by vdelendik** [comment]
fixed in scope of 1.5.2 pipeline patch release. verification still the same - verify launcher table in db

**Comment by okamara** [comment]
Verified on dev. branch. Fixed.
<img width="1043" alt="Снимок экрана 2021-06-18 в 15 00 49" src="https://user-images.githubusercontent.com/32964663/122557940-1b586c80-d046-11eb-9233-e22b2445feb7.png">
