### ISSUE TITLE
declare -Dselenium_url instead of host

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#155]
7.1.6+ carina deprecated selenium_host and use selenium_url as config parameter.
pipeline script should be adjusted accordingly

**Comment by vdelendik** [comment]
done, changes might be tested on qa or your private env where pipeline version for registration repository and execution is "develop".
To test:
1. make sure or update `ZEBRUNNER_VERSION=develop`
2. register new repository 
3. run any web job
-> review jenkins job console log:
1. no selenium_host value in logs
2. tests are executed successfully using new selenium_url param

**Comment by okamara** [comment]
verified on dev. branch with ZEBRUNNER_VERSION=develop;
Steps:
1. register new organization and repository  qaprosoft/carina-demo
2. run any web job
-> review jenkins job console log:
Actual result: selenium_host value in logs
Expected: no selenium_host value in logs
<img width="505" alt="Снимок экрана 2021-06-15 в 15 24 24" src="https://user-images.githubusercontent.com/32964663/122052763-b6570980-cdee-11eb-9d34-7e66f5cbd2a1.png">

**Comment by vdelendik** [comment]
@okamara, good catch.
In scope of #157 it was restored in 1.5.x pipeline as we have to support old carina versions for several months. so moving into the upcoming 1.7

**Comment by vdelendik** [comment]
done again. using `ZEBRUNNER_VERSION=develop` pipeline no more `selenium_host` in console log expected.

**Comment by okamara** [comment]
Verified on develop branch, fixed.
