### ISSUE TITLE
deprecate and remove useless carina storage related params

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#156]
Starting from 7.1.6+ we don't use any local storage path at all and provide to appium presign url onto s3 or appcenter directly.
It allows to remove similar params in pipeline
```
        S3_LOCAL_STORAGE("s3_local_storage", "/opt/apk"),
        APPCENTER_LOCAL_STORAGE("appcenter_local_storage", "/opt/apk"),
```

**Comment by vdelendik** [comment]
fixed. to test it make sense to execute android demo test on mCloud

**Comment by dhreben** [comment]
Verified.
