### ISSUE TITLE
support old notation with -Dselenium_host to have period when old carina works fine

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#157]
old carina can handle only selenium_host values so let's keep overrideing both values just in case to be able to run tests using old framework as well

**Comment by vdelendik** [comment]
fixed: 7.0.x and 7.1.x carina should be supported by 1.5.1 pipeline (branch: develop as ZEBRUNNER_VERSION)

**Comment by okamara** [comment]
Verified on dev. brach. Fixed.
