### ISSUE TITLE
Enhancement : Provision to run the management jobs under subfolders

### ISSUE THREAD

**Issue by prasadjshimpi** [zebrunner/pipeline-ce#158]
Enhancement: Currently whenever we are executing any of the management jobs they are getting executed under the root folder under Dashboard, There should be some provision exists that we should able to run the jobs under subfolders.

**Comment by vdelendik** [comment]
feature implemented. we can specify any sub-folder for org registration now: https://github.com/zebrunner/pipeline-ce/pull/163

to test we have to adjust obligatory:
1. manage jenkins -> configure system -> ZEBRUNNER_VERSION=develop
2. edit Management Jobs/RegisterOrganization replacing pipeline version in first line
```
@Library('Zebrunner-CE@master')
->
@Library('Zebrunner-CE@develop')
```
![image](https://user-images.githubusercontent.com/4551455/122541032-e3472e80-d031-11eb-8d7d-b7f4d09d6bf2.png)


after that we should test scenarios with different level of sub folders as org:
1. registerOrganization using empty org name, use RegisterRepository in root to register carina-demo and run tests
2. registerOrganization using "qps" as org name, use RegisterRepository in qps folder to register carina-demo and run tests
3. registerOrganization using complicated "org/org2/org3/org4" org name, use "org/org2/org3/org4/RegisterRepository" to register carina-demo and run tests

for all 3 cases org should be created by pipeline/jobdsl and every test you launch from those folders registered successfull yin reporting

**Comment by okamara** [comment]
Verified on dev. branch. Fixed.
