### ISSUE TITLE
remove qtest and testrail params and logic

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#165]
3rd party integration with tst case management tools moved into the reporting completely so we don't need to support it anymore on pipeline level.
We have to review and remove all TestRail and QTest jobdsl/pipeline code including params:
```
Configuration.Parameter.TESTRAIL_SERVICE_URL
Configuration.CREDS_TESTRAIL_SERVICE_URL
Configuration.CREDS_TESTRAIL
Configuration.Parameter.TESTRAIL_USERNAME
Configuration.Parameter.TESTRAIL_PASSWORD
```
and for QTest as well

**Comment by vdelendik** [comment]
done. to test setup zebrunner using develop branch and do basic acceptance.
as it is removal logic we should verify that using ZEBRUNNER_VERSION=develop we can register repositories and execute api/web tests successfully

**Comment by dhreben** [comment]
Verified.
Api/web - demo tests  successfully executed.
