### ISSUE TITLE
remove obsolete tcm integration part

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#175]
pro reporting is mature enough to make integration with testrail, x-ray etc on it's own.
in CE this functionality going to be removed to simplify codebase

**Comment by vdelendik** [comment]
done. during the testing just execute api/web and full-regression jobs using `ZEBRUNNER_VERSION=develop`

**Comment by okamara** [comment]
This ticket will be reverified and closed after fix https://github.com/zebrunner/pipeline-ce/issues/211
