### ISSUE TITLE
to migrate into 7.4.0 testng we have to add extra argument

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#184]
add `-Dtestng.strict.parallel=true` for TestNG runner.
https://github.com/zebrunner/carina/issues/1482

**Comment by vdelendik** [comment]
done. testing should be done using `ZEBRUNNER_VERSION=1.6.5` specified manually in jenkins global vars and using `7.2.12` carina as only it is released

**Comment by okamara** [comment]
Verified, fixed
<img width="933" alt="Снимок экрана 2021-11-10 в 18 20 22" src="https://user-images.githubusercontent.com/32964663/141143203-97e3af5b-2360-4ca6-9642-16a463b465b6.png">
.
