### ISSUE TITLE
adjust maser labeling based on 307+ jenkins changes

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#187]
https://www.jenkins.io/doc/book/managing/built-in-node-migration/

<html>
<body>
<div class="paragraph" style="box-sizing: border-box; color: rgb(74, 85, 104); font-family: lato, Roboto, &quot;Open Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem;">As part of the<span> </span><a href="https://groups.google.com/g/jenkinsci-dev/c/x5vdlJDvntw" style="box-sizing: border-box; color: rgb(0, 102, 153); text-decoration: none; background-color: transparent;">terminology cleanup effort</a>, the built-in node was renamed from "master node" to "built-in node" in Jenkins 2.307. This is not just a change affecting the UI and documentation: The node name affects the implicitly assigned label of the node (and consequently the<span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">NODE_LABELS</code><span> </span>environment variable), as well as the<span> </span><code style="box-sizing: border-box; font-family: SFMono-Regular, Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Courier New&quot;, monospace; font-size: 14px; color: rgb(232, 62, 140); word-break: break-word;">NODE_NAME</code><span> </span>environment variable.</p></div><div class="admonitionblock note" style="box-sizing: border-box; color: rgb(74, 85, 104); font-family: lato, Roboto, &quot;Open Sans&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

  | The NODE_NAME environment variable in Pipelines is set by the Pipeline: Nodes and Processes plugin. In plugin version 2.39 and earlier, this value is always master. Update to version 2.40 or newer to get consistent behavior between job types
-- | --

</div>
</body>
</html>

**Comment by azarouski** [comment]
Solved in PR https://github.com/zebrunner/jenkins-master/pull/385
