### ISSUE TITLE
unable to override provider capabilities

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#190]
Three below args can't be overridden via overrideFields:
```
capabilities.enableVideo
capabilities.enableLog
capabilities.enableVNC
```

in spite o f the fact that our provider specific caps are standard we have to provide an option to override them if needed

**Comment by vdelendik** [comment]
fixed and tested on mine own

**Comment by vdelendik** [comment]
fix corrupted default provider capabilities setup, reopening for investigation

**Comment by vdelendik** [comment]
fixed correctly to keep regular mcloud capabilities workable: https://github.com/zebrunner/pipeline-ce/pull/203/files

**Comment by okamara** [comment]
Verified on develop branch, fixed.
