### ISSUE TITLE
fix doc site urls for system jobs

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#192]
onPullRequrst, onPush and build system jobs have invalid link to the community edition guide:

https://zebrunner.github.io/zebrunner/config-guide/#setup-webhook-events-push-and-pull-requests
but should be
https://zebrunner.github.io/community-edition/config-guide/#setup-webhook-events-push-and-pull-requests

**Comment by vdelendik** [comment]
fixed. all 3 system jobs should have the same link in description, for example:
![image](https://user-images.githubusercontent.com/4551455/140660235-66491ade-1b98-4c5c-8f01-5451df04c07a.png)

testing should be done using ZEBRUNNER_VERSION: 1.6.5 (updated manually in jenkins global variables)

**Comment by okamara** [comment]
Verified.Fixed
<img width="587" alt="Снимок экрана 2021-11-10 в 17 05 20" src="https://user-images.githubusercontent.com/32964663/141127650-9fb34321-19a7-4658-b2b3-d83c8b30cd14.png">
<img width="646" alt="Снимок экрана 2021-11-10 в 17 05 11" src="https://user-images.github
<img width="636" alt="Снимок экрана 2021-11-10 в 17 05 00" src="https://user-images.githubusercontent.com/32964663/141127709-5b536623-cc3b-4277-a979-b643caa0fb77.png">
usercontent.com/32964663/141127680-c4c3252e-0548-4128-bfe6-60aa30b664ed.png">
.
