### ISSUE TITLE
rename com.qaprosoft package to com.zebrunner

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#2]
subj

**Comment by vdelendik** [comment]
https://github.com/zebrunner/pipeline-ce/pull/26

as test scenario:
1) configure 'Zebrunner-CE' pipeline library using modern scm
2) url should be specified without variable! i.e. https://github.com/zebrunner/pipeline-ce.git
3) try to scan and execute api and web test

**Comment by dhreben** [comment]
Verified.
