### ISSUE TITLE
implement any variables registration per organization folder on CI

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#201]
So far we register reporting credentials via registerOrganization or registerReportingCredentials as jenkins global credentials.
So it is secure enough to store token but secured url is too much.

Let's reuse possibility to attach config properties files onto the jenkins organization folder instead so every admin of the org might easily review and change if needed either manually or using registerReportingCredentials job.

1. generate `agent.properties` file with content like:
```
REPORTING_ENABLED=true
REPORTING_SERVER_HOSTNAME=https://demo.zebrunner.org
REPORTING_SERVER_ACCESS_TOKEN=<token>
```
2. attach this file into the folder config files
3. adjust pipeline to push on the start right after the cloning to `src/test/resources` by default
    Note: provide functionality to override this value correctly

as an extra option test copying just into the current directory or copy into the every srs/test/resources recursively

**Comment by vdelendik** [comment]
let's redesign approach a little bit and follow docker practice which operates `variables.env` files.
so it is recommended to generate such `variables` env custom config file everytime we register organization folder.
inside this file by default let's put:
1. reporting env vars:
```
REPORTING_ENABLED=true
REPORTING_SERVER_HOSTNAME=https://demo.zebrunner.org
REPORTING_SERVER_ACCESS_TOKEN=<token>
```
2. all custom selenium hub urls per provider aka:
```
ZEBRUNNER.SELENIUM_URL=...
SAUCELABS.SELENIUM_URL=...
```
3. pipeline should read this de fault `variables.env` from the folder and convert into the environment variable for maven

As a benefit org admin might add all kind of customization including session crypto keys, custom TCM integration parameters etc

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/pipeline-ce/pull/214

simplified a lot integration with reporting making it via env vars per organization/folder.
during the testing we have to 
1. switch manually `ZEBRUNNER_VERSION=develop` for global env
2. switch pipeline version from master to develop for RegisterOrganization and RegisterRepository jobs in Management_Jobs
3. register new organization providing valid repo url and token
-> open config files for registered repo and see agent.env with valid content you provided
![image](https://user-images.githubusercontent.com/4551455/150038930-4ed0a6c7-df2d-4f54-a5d4-baa55d06b688.png)
4. run api/web jobs
-> jobs are registered in reporting
5. try to registerOrganization with empty repo url and/or token and scan repo
-> organization and repo should be created, jobs executed but results not published to reporting
-> html ZafiraReport should absent on all api or web jobs
6. play with registerReportingCredentials to be able to override url/token for reporting
7. play with empty values for registerReportingCredentials

**Comment by okamara** [comment]
Verified, fixed.
