### ISSUE TITLE
remove `driver_recorder` custom maven property

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#205]
it was added temporary to support 6.x and 7.x carina version. As only we start with 8.x carina 6th will be deprecated and not supported anymore so we could remove this custom maven arg as well

**Comment by vdelendik** [comment]
Removed `driver_recorder=false` option. to test just setup CE and registerRepository using `ZEBRUNNER_VERSION=develop`.
Run any job and inspect console log: no `driver_recorder` anymore inside!

**Comment by okamara** [comment]
Verified, console log is without "driver_recorder"
