### ISSUE TITLE
hide maven download details from console logs

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#207]
there is n sense to have everytime details about all downloaded items as user has to scroll down to start viewing business logs.
let's find a way to hide this details and keep them only when `ZEBRUNNER_LOG_LEVEL=DEBUG`

https://stackoverflow.com/questions/21638697/disable-maven-download-progress-indication

**Comment by vdelendik** [comment]
done, testing should be done using `ZEBRUNNER_VERSION=develop`.
1. update in manage jenkins -> configure system global env var
2. register repository from scratch
3. run any job on recently deployed/started env
-> no INFO console information about downloading artifacts. Only WARNING might present in case of any problem.
Also even after enabling DEBUG log level we don't want to display downloading info anymore!

**Comment by okamara** [comment]
Verified, fixed.
