### ISSUE TITLE
provide organizational env vars readers by pipeline

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#208]
we should be able to read concrete config files from org folder or globally and transfer them into the env var for any runner.
let's consider to support as of now:
agent.env
variables.env

agent.env - that's a place for registering reporting global data, variables.env - any org specific variables accessible for admins only

writer part is described in https://github.com/zebrunner/pipeline-ce/issues/201

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/pipeline-ce/pull/214

simplified a lot integration with reporting making it via env vars per organization/folder.
during the testing we have to 
1. switch manually `ZEBRUNNER_VERSION=develop` for global env
2. switch pipeline version from master to develop for RegisterOrganization and RegisterRepository jobs in Management_Jobs
3. register new organization providing valid repo url and token
-> open config files for registered repo and see agent.env with valid content you provided
![image](https://user-images.githubusercontent.com/4551455/150038930-4ed0a6c7-df2d-4f54-a5d4-baa55d06b688.png)
4. run api/web jobs
-> jobs are registered in reporting
5. try to registerOrganization with empty repo url and/or token and scan repo
-> organization and repo should be created, jobs executed but results not published to reporting
-> html ZafiraReport should absent on all api or web jobs
6. play with registerReportingCredentials to be able to override url/token for reporting
7. play with empty values for registerReportingCredentials

**Comment by okamara** [comment]
Verified on develop, fixed.
