### ISSUE TITLE
ClassNotFoundException while Register organization for ZEBRUNNER_VERSION=develop

### ISSUE THREAD

**Issue by okamara** [zebrunner/pipeline-ce#210]
Steps:
1. Set up zebrunner from develop branch
2. Open Configuration page in jenkins and set ZEBRUNNER_VERSION=develop
3. Run Register organization 
Actual result:  ClassNotFoundException while Register organization for ZEBRUNNER_VERSION=develop
Expected: Organization is created

**Comment by vdelendik** [comment]
I forgot to mention that updates in Management_Jobs require manual intervention and changing zebrunner version in these jobs as well from master to develop..
