### ISSUE TITLE
move provider property outside of capabilities

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#212]
provider is non w3c capabilities and better not to use provide it into the capabilities at all.
we've found a way to register as minimal for mcloud default capabilities on appium level and these caps can't be overridden by user/job

**Comment by vdelendik** [comment]
done. no more hardcoded capabilities provider settings via piepline!
to test you have to 
1. setup CE from develop
2. update in jenkins global variables `ZEBRUNNER_VERSION=develop`
3. update Management_Jobs/registerOrganization pipeline code changing master -> develop and execute it
4. update <org>/registerRepository pipeline code changing master->develop and execute it (90% it should be generated with develop after above steps)
-> verify Mobile-Android-Demo-Test hidden params. Hidden input field `provider` should exists, `cpabilities.provider` should not!
5. run Mobile-Android-Demo-Test job using `develop` branch where 7.3.15-SNAPSHOT carina is used
-> job should be executed, some steps might fail but logs, exception and video and session.log artifacts should present in reporting
-> review job console log output and confirm that there is no more such caps inside:
capabilities.enableVideo=true
capabilities.enableLog=true
capabilities.enableVnc=false

**Comment by okamara** [comment]
verified, fixed.
