### ISSUE TITLE
update github org to use zebrunner inside default jobs

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#213]
RegisterRepository still uses qaprosof/carina-demo link. let's inspect and replace by zebrunner

**Comment by vdelendik** [comment]
fixed for generated RegisterRepository job inside org folder. to test make sure to switch into `ZEBRNNER_VERSION=develop` and update management_jobs pipeline to develop as well
1. register org
2. run org/RegisterRepository
-> repoUrl should refer to carina-demo using `https://github.com/zebrunner/carina-demo.git` zebrunner org

**Comment by okamara** [comment]
Verified on develop branch
