### ISSUE TITLE
unable to register org and reporting credentials for root org folder

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#215]
above jobs crashed after implementing #201 and #208. we have to find a way to manage global custom config folders when empty folder name is provided

**Comment by vdelendik** [comment]
fixed. register org with empty folder naem and valid reporting url/token.
register repo in root folder and run api/web job
-> jobs executed, tests registered in reporting
-> goto Manage Jenkins -> Manage files and verify that `agent.env` with valid reporting integrations registered

**Comment by okamara** [comment]
Verified on develop branch, fixed.
