### ISSUE TITLE
restore `capabilities.provider` for 1.7 release to fix video and session loggers for selenoid

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#219]
as carina still on 7.5.1 appium java client we can postpone removal of non w3c `capabilities.provider` property.
so let's again make it as hidden capabilities.provider and remove completely in 2.0.

Also there is NO sense to generate default capabilities. already applied in 1.7: https://github.com/zebrunner/pipeline-ce/commit/053df41225ea5a1f66ea6065050b99b30f8fa28c

**Comment by vdelendik** [comment]
attempt to restore didn't help to reanimate video recordings so no need to make it happen as anyway reporting changes required

**Comment by vdelendik** [comment]
fixed without any updates on reporting side. changes tested successfully on http://18.204.139.166/test-runs/4 env.

**Comment by okamara** [comment]
Verified, fixed.
