### ISSUE TITLE
implement variables.env reader per repo

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#220]
so far to be able to override any env var by admin per repo we decided to implement `variables.env` env reader from config file and appending vars into the inited from `agent.env`.
so far modification of the file might be done only by administrators who have access to CI.

**Comment by vdelendik** [comment]
done, testing better to organize on CE using develop branch. Make sure to update in advance `ZEBRUNNER_VERSION=develop` before org registration

**Comment by okamara** [comment]
verified on ce, fixed.
