### ISSUE TITLE
remove default `-Dtestng.strict.parallel=true` tetsng arg

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#234]
for those who wanna to use it they can add in their pom.xml...

**Comment by vdelendik** [comment]
done. to test setup CE using branch develop, update ZEBRUNNER_VERSION=develop in jenkins global vars.
scan and execute any carina-demo job
-> no more `-Dtestng.strict.parallel=true` in the maven cli args, i.e.
`mvn -B -U --no-transfer-progress  -Dtestng.strict.parallel=true ...`
->
`mvn -B -U --no-transfer-progress  ...`

**Comment by okamara** [comment]
Verified, fixed.
<img width="733" alt="Снимок экрана 2022-03-18 в 16 46 55" src="https://user-images.githubusercontent.com/32964663/159014719-ee2eefa5-216f-4d23-9cb3-8bceb97de403.png">
