### ISSUE TITLE
regression: content of *.dumpstream files not showed

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#236]
In case of any failure with java we don't shown dumpstream content as part of console job logs:
target/surefire-reports/2022-03-15T22-21-02_787.dumpstream
target/surefire-reports/2022-03-15T22-21-02_787-jvmRun1.dumpstream

Also think about publishing them as artifacts

**Comment by vdelendik** [comment]
updated glob filter to be able to find *.dump and *.dumpstream files:
```
context.findFiles(glob: '**/*.dump*')
```

**Comment by okamara** [comment]
Verified, fixed.
