### ISSUE TITLE
add the ability to use the extensibleChoice parameter in suites

### ISSUE THREAD

**Issue by afedorova157** [zebrunner/pipeline-ce#237]
Idea of this enhancement is to allow users to pass some groovy scripts expressions directly in test suites, e.g. 
`<parameter name=“extensibleChoice::testrail_run_name::my” value=“import static java.util.Calendar.*\ndef date = new Date().format(‘MM/dd/yyy’)\nreturn [‘Reviews_pages_release_run_WEB_’ + date]” />`

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/pipeline-ce/pull/238

for mat of declaring extensible choice via suite xml is:
```
<parameter name="extensibleChoice::myExtensibleChoice::myDesc" value="import static java.util.Calendar.*;def date = new Date().format('MM/dd/yyy');return ['Release_date' + date]" />
```
make sure to use `;` symbol as lines break as `\n` is not supported!

**Comment by okamara** [comment]
Verified, fixed.
