### ISSUE TITLE
simplify `jenkinsPipelineEnvironments` usage with potential removal

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#240]
let's review usage of `jenkinsPipelineEnvironments` suite xml param and try to remove it completely.
it was used as a limitation for the environments during mass start. it seems like this particular feature might be covered as part of jenkinsRegressionMatrix where we can provide any param including env.

**Comment by vdelendik** [comment]
done. to test we have to 
1. setup CE (master or develo branch - doesn't matter)
2. switch ZEBRUNNER_VERSION=develop
3. scan carina-demo
4. execute all cron regression jobs: api_regression, web_regression, mobile_regression and full_regression
-> jobs should be executed as in previous releases
5. execute for example api_regression one more time but provide as env: `DEMO,PROD` - comma separated 2 values
-> cron should start every registered job twice for each env, i.e. instead of 2 jobs - 4 should be triggered
6. execute using env: `DEMO,BETA,PROD`
-> 6 jobs should be triggered.

**Comment by okamara** [comment]
Verified, fixed.
