### ISSUE TITLE
API jobs are failed as *.dumpstream,*.dump are present in job logs

### ISSUE THREAD

**Issue by okamara** [zebrunner/pipeline-ce#243]
Steps:
1. Run Api job or API regression via Jenkins
2. Verify Test run results in Reporting 
3. Verify Test job logs via Console output in Jenkins
Actual result: API jobs are failed as *.dumpstream,*.dump are present in job logs
Expected:  *.dumpstream,*.dump should not fail test job
<img width="1096" alt="Снимок экрана 2022-03-18 в 16 07 03" src="https://user-images.githubusercontent.com/32964663/159008313-db51d925-c8b5-4017-8d5a-3fc8f8e86ce7.png">
<img width="1372" alt="Снимок экрана 2022-03-18 в 16 06 31" src="https://user-images.githubusercontent.com/32964663/159008397-5609a1bf-a071-4e94-8d48-1e11eadd7703.png">

**Comment by vdelendik** [comment]
fixed. printing any dumpstream shouldn't fail a build starting from 1.7.2

**Comment by okamara** [comment]
Verified, fixed.
