### ISSUE TITLE
find a way to override global env vars on folder level via config files

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#253]
to execute mavem/testng commands we already implemented #220 feature.
let's do research for jobdsl as well to be able to override such items as
* ZEBRUNNER_PIPELINE
* ZEBRUNNER_VERSION
* ADMIN_EMAILS
* SONAR_URL

maybe separated ticket for below property should be added:
* ZEBRUNNER_LOG_LEVEL

**Comment by vdelendik** [comment]
done. all above variables might be overridden via `variables.env` config file on organizational folder, for example: http://52.7.165.168/jenkins/job/qps/configfiles/editConfig?id=variables.env

**Comment by okamara** [comment]
verified on CE, fixed.
