### ISSUE TITLE
be able to use selenium_url from provider for onPush jobs

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#262]
during onPush we wanna to start testing for simple UI as well.
so we have to incorporate selenium_url update based on provider for testNG->onPush

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/pipeline-ce/commit/528102a1809745eda8e3fdfe2c8046b1f3e895db

**Comment by okamara** [comment]
verified, selenium_url is not present

**Comment by vdelendik** [comment]
resolving again. @okamara - when your env is ready - sync with me. I'll show you how to setup it correctly, manual intervention is required to make this feature workable. 
We ok with manual step because it simplify set of management jobs in smarter way...

**Comment by okamara** [comment]
Verified,fixed.
