### ISSUE TITLE
commentSha method in github client has context hardcoded 

### ISSUE THREAD

**Issue by fkhan2** [zebrunner/pipeline-ce#270]
[This](https://github.com/zebrunner/pipeline-ce/blob/7af0e9e9ab3c0ee4042f0e23532fbdaa367134ba/src/com/zebrunner/jenkins/pipeline/integration/github/GitHubClient.groovy#L18) prevents context passed as argument to be irrelevant.

**Comment by vdelendik** [comment]
we have to parametrize it and make `build` if nothing provided. Goal for this method was to organize extra build and compile verification to block uncompiled code from merging with ability to show it as sperate status check.

**Comment by azarouski** [comment]
commentSha method was modified to simplify and improve its usage.
Also some documentation for usage GitHub client was added.

**Comment by okamara** [comment]
verified
