### ISSUE TITLE
rename ZafiraReport by ZebrunnerReport during publishHTML

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#274]
subj

**Comment by azarouski** [comment]
ZafiraReport was renamed to ZebrunnerReport
for more info please see PR #280

**Comment by vdelendik** [comment]
merged. @okamara - you can test using CE and `develop` branch for the `ZEBRUNNER_VERSION`.

**Comment by okamara** [comment]
verified, fixed.
