### ISSUE TITLE
finish TODO for maven html report publishing

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#276]
https://github.com/zebrunner/pipeline-ce/blob/1937f288e77d40fa61e1bcd9f643088e1152eb02/src/com/zebrunner/jenkins/pipeline/runner/maven/TestNG.groovy#L876

**Comment by azarouski** [comment]
https://github.com/zebrunner/pipeline-ce/pull/277

**Comment by vdelendik** [comment]
testing should be done over CE using develop branch for pipeline.

**Comment by vdelendik** [comment]
already n prod
