### ISSUE TITLE
Error when trying to create snapshot via onPush

### ISSUE THREAD

**Issue by akamarouski** [zebrunner/pipeline-ce#283]
When I tried to explicitly call onPush to create a snapshot, I got an error
`java.lang.IllegalArgumentException: Null value not allowed as an environment variable: zafiraFields`
At the same time, there is no such error when registering the repository.

When registering a repository, the `zafiraFields` parameter contains a `null` value. However, if explicitly call onPush, then this field is empty, which may cause an error.

**Comment by vdelendik** [comment]
it should be fixed in upcoming 2.0

**Comment by okamara** [comment]
verified, fixed.
