### ISSUE TITLE
scheduling jobdsl requires updates

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#287]
we have to review our pipelines and move trigger schedules into new `proeprties` block
https://github.com/jenkinsci/job-dsl-plugin/wiki/Migration#migrating-to-177

**Comment by okamara** [comment]
verified, scheduling is not present inside 
![Uploading Снимок экрана 2023-03-21 в 20.55.51.png…]()

**Comment by okamara** [comment]
verified, fixed.
