### ISSUE TITLE
replace QPS_PIPELINE_* vars by new

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#29]
old one:
ENV QPS_PIPELINE_GIT_URL=https://github.com/qaprosoft/qps-pipeline.git
ENV QPS_PIPELINE_GIT_BRANCH=5.3
QPS_PIPELINE_LOG_LEVEL=INFO

related new ones:
ENV ZEBRUNNER_PIPELINE=https://github.com/zebrunner/pipeline-ce.git
ENV ZEBRUNNER_VERSION=develop
ZEBRUNNER_LOG_LEVEL=INFO

**Comment by vdelendik** [comment]
done. in scope of the ticket renamed:
QPS_PIPELINE_GIT_URL -> ZEBRUNNER_PIPELINE
QPS_PIPELINE_GIT_BRANCH -> ZEBRUNNER_VERSION
QPS_PIPELINE_LOG_LEVEL -> ZEBRUNNER_LOG_LEVEL

also pipelineLibrary var for Repository.groovy and TestNG.groovy had to be renamed to pipeline as "pipelineLibrary" seems system.

@dhreben to test, please setup from zebrunner/zebrunner (branch: develop) and do a sanity check

**Comment by dhreben** [comment]
Verified.
