### ISSUE TITLE
onPush job failed during register repo 

### ISSUE THREAD

**Issue by okamara** [zebrunner/pipeline-ce#290]
Steps:
Execute Register repo carina-demo branch "master"
Actual result: onPush job failed during register repo 
Error from log:
` [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project carina-demo: Not authorized. Analyzing this project requires authentication. Please provide a user token in sonar.login or other credentials in sonar.login and sonar.password. -> [Help 1]
19:57:02  [ERROR] 
19:57:02  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
19:57:02  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
19:57:02  [ERROR] 
19:57:02  [ERROR] For more information about the errors and possible solutions, please read the following articles:
19:57:02  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

**Comment by vdelendik** [comment]
let's test again using 9.5.0 sonarqube which is included into the CE, branch: develop
