### ISSUE TITLE
pipeline-ce: decommission usage of master label

### ISSUE THREAD

**Issue by azarouski** [zebrunner/pipeline-ce#291]
Due to new Jenkins policy of development we need to eventually remove label named "master"

**Comment by azarouski** [comment]
PR https://github.com/zebrunner/pipeline-ce/pull/304

**Comment by azarouski** [comment]
and PR https://github.com/zebrunner/jenkins-master/pull/395

**Comment by okamara** [comment]
Verified on develop branch, master mode is not present any more. Build-in-node is present
<img width="222" alt="Снимок экрана 2023-06-26 в 15 56 42" src="https://github.com/zebrunner/pipeline-ce/assets/32964663/b03abdf7-c5d8-49a9-88e2-4277c8ed0857">
