### ISSUE TITLE
disable sonar analysis if SONAR_TOKEN not available

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#299]
due to the upgraded sonarqube to 9.8.0 we need SONAR_TOKEN obligatory to start static code analysis.
if no token discovered we have to skip analysis otherwise we see:
```
12:43:48  [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default-cli) on project carina-demo: Not authorized. Please check the properties sonar.login and sonar.password. -> [Help 1]
12:43:48  [ERROR] 
12:43:48  [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
12:43:48  [ERROR] Re-run Maven using the -X switch to enable full debug logging.
12:43:48  [ERROR] 
12:43:48  [ERROR] For more information about the errors and possible solutions, please read the following articles:
12:43:48  [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by vdelendik** [comment]
done. by default after setup CE from develop we have disabled sonar integration. only after finishing https://github.com/zebrunner/community-edition/blob/develop/docs/integration/scm.md and https://github.com/zebrunner/community-edition/blob/develop/docs/integration/sonarqube.md static code analysis and pull request checker should appear

**Comment by okamara** [comment]
verified, fixed.
