### ISSUE TITLE
setup pipeline integration using "Modern SCM" integration

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#3]
For now we setup qps pipeline integration using legacy SCM approach:
![image](https://user-images.githubusercontent.com/4551455/95752775-37329400-0ca9-11eb-8672-4cee9f85741e.png)

Goal of the ticket:
1) investigate the benefits of the modern scm integration
2) try to setup it manually on your env
As result I want to get automatic integration for any pipeline version like 5.2 and 5.3 together

3) identify required steps to update jobs to run tests using different pipeline version

**Comment by vdelendik** [comment]
changes correctly applied to the zebrunner/zebrunner (branch: develop).

**Comment by dhreben** [comment]
Verified.
