### ISSUE TITLE
reuse main instead of master branch

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#301]
1. master should be stay as is to support v1.8 pipeline
2. all 2.0 changes should be merged into the new `main` branch
3. update jenkins-master managerial job to use `main` instead of `master`

**Comment by vdelendik** [comment]
done for pipeline-ce: https://github.com/zebrunner/pipeline-ce/pull/292
for jenkins-master submitted new ticket: https://github.com/zebrunner/jenkins-master/issues/390

**Comment by okamara** [comment]
Verified, reopened related ticket. This ticket going to close.
