### ISSUE TITLE
Sonar shows warning "Property 'sonar.jacoco.reportPaths' is no longer supported. Use JaCoCo's xml report and sonar-jacoco plugin."

### ISSUE THREAD

**Issue by okamara** [zebrunner/pipeline-ce#306]
<img width="367" alt="Снимок экрана 2023-04-27 в 22 24 05" src="https://user-images.githubusercontent.com/32964663/234970493-e737cb04-5f6c-4d92-9c5a-b442b47868c0.png">
<img width="596" alt="Снимок экрана 2023-04-27 в 21 46 35" src="https://user-images.githubusercontent.com/32964663/234970528-fef527e4-4536-4485-a332-fa56bff05fd0.png">

**Comment by azarouski** [comment]
PR #309

**Comment by okamara** [comment]
Verified, fixed

**Comment by okamara** [comment]
<img width="1440" alt="Снимок экрана 2023-06-29 в 14 21 34" src="https://github.com/zebrunner/pipeline-ce/assets/32964663/571bbe7b-9d5f-45d6-a41a-cbce82252c8b">
