### ISSUE TITLE
remove obsolete queue_registration param

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#320]
https://github.com/zebrunner/pipeline-ce/blob/f3199c4b4697323b151004ac79742973bc23ebee/src/com/zebrunner/jenkins/pipeline/runner/maven/TestNG.groovy#L721

let's remove it as we don't use it

**Comment by vdelendik** [comment]
done. basic acceptance of the community-edition from branch develop should be ok.
make sure jenkins-master is 2.2 already

**Comment by dhreben** [comment]
Basic acceptance  with iOS-Preferences-Test ,Mobile-iOS-Safari-Test ,  Android-Demo-Test  successfully completed. Video, screenshots and logs are available.
