### ISSUE TITLE
hardcoded org name detected

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#34]
https://github.com/zebrunner/pipeline-ce/blob/cf581b4c2675c3faef9e2a1fa75d83992a93ee06/src/com/zebrunner/jenkins/pipeline/integration/sonar/SonarClient.groovy#L37

**Comment by sandinosanchez** [comment]
delivered in #35 combined test test cases will be published in #5

**Comment by vdelendik** [comment]
closed analyzing pr
