### ISSUE TITLE
remove "screen_record_host" as not needed property anymore

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#37]
there is no sense to save absolute url to the recorded log, video etc artifacts. it is enough to register relative path and redirect on webserver layer to valid location. Potentially it should help to integrate references to browserstack artifacts etc without extra development

**Comment by vdelendik** [comment]
fixed. no need to provide this value anymore!
to test we have to run web-demo-test using overridded 
carina-core_version=6.4.44-SNAPSHOT
Video recording should be available after run for each test

**Comment by dhreben** [comment]
Verified.
