### ISSUE TITLE
Webhook tokens should be deleted upon organisation removal

### ISSUE THREAD

**Issue by sandinosanchez** [zebrunner/pipeline-ce#41]
If you delete an organisation the tokens generated for each git type for that org should be deleted.

**Comment by sandinosanchez** [comment]
Delivered in #42 

**Objective**

 - Verify the removal of webhook tokens when deleting an organisation(using DeleteOrganization Management job)

**Environment**

 - Zebrunner-ce > develop

**Test Scenario:**

 1. Run RegisterOrganization Job
 2. Run Register repository at leas two times one for carina-demo github and the other for gitlab.
 3. Go to **Manage Jenkins > Manage Credentials** and verify that among all the creds there should be two named:
    - orgName-github-webhook-token
    - orgName-gitlab-webhook-token
  4. Go to **ManagementJobs > DeleteOrganization** run the job with your org name
  5. Go to **Manage Jenkins > Manage Credentials** and the creds from **step 3** should be gone

**Expected results**

 6. The webhook creds for the org are deleted provided the successful execution of DeleteOrganization job.

**Comment by dhreben** [comment]
Fixed.
Verified on develop branch.
