### ISSUE TITLE
invalid default selenium_host is used right after setup

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#45]
instead of local selenoid url I see that old default one is used:
`02:49:03  selenium_host=http://demo:demo@demo.qaprosoft.com/selenoid/wd/hub`

Workaround: register valid value for selnium using registerHubCredentials management job.

**Comment by vdelendik** [comment]
fixed. root cause - invalid jenkins configuration from scratch for 1.2 version.
to retest, please, obligatory remove old jenkins-master 1.2 image to redownload with a fix!

**Comment by dhreben** [comment]
Fixed.
