### ISSUE TITLE
temporary restore screen_record_host variable to support old carina runs

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#48]
To support smooth movement for those who has selenoid clusters configured we have to return screen_record_host parameter temporary to be used by carina 6.4 generation. And schedule removal of the property let's say in 1.5

**Comment by vdelendik** [comment]
done. fix merged into the ZEBRUNNER_PIPELINE: 1.2
to test is you can run web test and look for valid value in console log for
```
screen_record_host=http://ip-address/video/%s
```

**Comment by dhreben** [comment]
Fixed.
