### ISSUE TITLE
Credentials in Jenkins are not removed after delete organization from admin

### ISSUE THREAD

**Issue by okamara** [zebrunner/pipeline-ce#61]
Steps:
1. Create organization olgatest3 in https://qaprosoft.farm/
2. Scan repository
3. Run Ape demo test, Web demo test, Web regression run, 
API-XlsDataProvider-Retry (33% pass rate) via launcher
4. Link failed test cases with bugs in Jira (Integration with JIRA is ON)
5. Delete organization olgatest3
6. Verify that organization and all credentials are removed on Jenkins side:
https://ci.qaprosoft.farm/configureSecurity/
https://ci.qaprosoft.farm/credentials/
https://ci.qaprosoft.farm/securityRealm/

Actual result: https://ci.qaprosoft.farm/credentials/ - creds are note deleted
<img width="1114" alt="Screen Shot 2020-11-16 at 4 09 16 PM" src="https://user-images.githubusercontent.com/32964663/99257195-b0348680-2827-11eb-85c5-29bc9fafd2fb.png">

Expected: all credentials are deleted

**Comment by vdelendik** [comment]
fixed. it might be tested on current stage jenkins

**Comment by dhreben** [comment]
Fixed
