### ISSUE TITLE
onPullrequest job status should be registered in SCM as extra status

### ISSUE THREAD

**Issue by okamara** [zebrunner/pipeline-ce#64]
we lost possibility to control github merge status for compilation failures...
earlier github pull request checker registered "default" state based on results of the compilation. it was used to prevent merginh compilation failure. For now temporary disabled this requirement

**Comment by vdelendik** [comment]
finally found a way to return comments for the github as minimal as for PR checker so for onPush as well.
tested on mine own as feature might be reused only as part of private pipelines
