### ISSUE TITLE
move SmartJobsRerun to use TestNG runner instead of QARunner

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#7]
QARuner is deprecated so we have to use TestNG runner

**Comment by vdelendik** [comment]
done. TestNG runner is specified for this job.
it might be tested on zebrunner/zebrunner (branch: develop):
1. Management_Jobs/SmartJobsRerun inside configure should have such code
`
@Library('Zebrunner-CE@develop')
import com.zebrunner.jenkins.pipeline.runner.maven.TestNG;
new TestNG(this).rerunJobs()
`
2. run web regression and corrupt 1-2 tests via vnc session, for example closing browsers
3. rerun web regression using SmatJobsRerun and see that only appropriate failures restarted

**Comment by dhreben** [comment]
Closed
Open new ticket https://github.com/zebrunner/pipeline-ce/issues/33
