### ISSUE TITLE
Changes in code is not applied in github pull request

### ISSUE THREAD

**Issue by okamara** [zebrunner/pipeline-ce#70]
Steps:
1. Set up integration with jenkins, github, sonarqube
2. Create pull request in Github with errors in code
3. Fix issues in code and commit changes in the same branch
4. Verify that Pull request is sent with code fixes
Actual result: pull request is sent with old code without fixes

**Comment by vdelendik** [comment]
fixed. we should use latest sha1 commit to start verification

test scenario as descibed above:
1. send PR from the source branch with some sonar issue
-> pr checker executed and showed sonar complains
2. push into the source branch fixes for the complain
-> pr checker started ahain on it's own
-> new sources are analyzed and if issues fixes - verification should be green

**Comment by okamara** [comment]
Fixed. Tested on develop branch.
