### ISSUE TITLE
adjust slave label detection using runner class instead of job type

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#71]
job type is TestNG related property. In 1.1 jenkins-slave we already improve a lot to make it build tool dependent.
So let's change the logic and assign label based on runner class, i.e. maven and gradle as of now.
Also we have to keep the logic for assigning custom labels

**Comment by vdelendik** [comment]
done.
during testing make sure to use ZEBRUNNER_VERSION=develop before scanning and jobs execution.
web and api jobs should be started and executed correctly in result

**Comment by dhreben** [comment]
Verified.
