### ISSUE TITLE
unable to register non carina-demo repo via test launcher ui

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#72]
we have to sync between reporting and pipeline new repoUrl args.

**Comment by vdelendik** [comment]
fixed.
test scenario:
1. setup zebrunner/zebrunarre from develop branch from scratch (provide github intetgration detals).
2. Via test laucnher ui try to add non carina-demo repository

**Comment by dhreben** [comment]
Fixed.Open new ticket https://github.com/zebrunner/pipeline-ce/issues/82
