### ISSUE TITLE
investigate possibility to remove GITHUB_* from Configuration enum

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#8]
GITHUB host, org etc are registered globally per jenkins instance. We have to refactor pipelines to be able to reuse any scm on the fly based on actual repo scan. By default each job already has hidden arg for that so gloval vars might be removed completely.

**Comment by vdelendik** [comment]
Fully redesigned cloning functionality and used arguments: https://github.com/zebrunner/pipeline-ce/pull/36/
Such global vars were removed completely:
        GITHUB_HOST("GITHUB_HOST", "github.com"),
        GITHUB_API_URL("GITHUB_API_URL", "https://api.\${GITHUB_HOST}/"),
        GITHUB_ORGANIZATION("GITHUB_ORGANIZATION", "qaprosoft"),
        GITHUB_HTML_URL("GITHUB_HTML_URL", "https://\${GITHUB_HOST}/\${GITHUB_ORGANIZATION}"),
        GITHUB_OAUTH_TOKEN("GITHUB_OAUTH_TOKEN", mustOverride, true),
        GITHUB_SSH_URL("GITHUB_SSH_URL", "git@\${GITHUB_HOST}:\${GITHUB_ORGANIZATION}"),

to test is use zebrunner/zebrunner from develop branch.

**Comment by dhreben** [comment]
Verified
