### ISSUE TITLE
make description of the generic webhook plugin unique

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#84]
when we assign token for generic webhook we use descritpnio which is a constant for us. Let's rename it to something project/org/repo related

**Comment by vdelendik** [comment]
done. during the testing please check that each new repository register github/gitlab/bitbucket token using new format.
old values
```
id: project-github-webhook-token
desc: Token used to configure generic webhook triggers
```

new values:
```
id: project-github-webhook-token
desc: project-github-webhook-token
```
Note: instead of project actual repo name should be used.
changes applied as inside pr checker jobs credentials are selected by descritption

**Comment by okamara** [comment]
Fixed.
