### ISSUE TITLE
"repo" argument not available from configuration

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/pipeline-ce#88]
We moved to the improved git integration via repoUrl. we have to examine all Configuration.get("repo") usages and replace it if possible by "this.repo" parameter which is calculated in BaseObject.groovy.

Example:
https://github.com/zebrunner/pipeline-ce/blob/6073242c3151c9a63dbc6f2714f4eb769dcbce7f/src/com/zebrunner/jenkins/pipeline/runner/maven/TestNG.groovy#L948

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/pipeline-ce/commit/1a028cc074d64b9c5e83d0d7db282679fd5fa5f7

as a test run job and cron. in jenkins build number still should contain build number, repo name and branch
setDisplayNameTemplate("#${buildNumber}|${this.repo}|${branch}")

**Comment by okamara** [comment]
Verified on develop branch
<img width="354" alt="Screen Shot 2020-12-10 at 3 59 00 PM" src="https://user-images.githubusercontent.com/32964663/101775599-c79e2100-3b00-11eb-9980-cc73973484be.png">
@vdelendik is it expected?
